/**
 * Step: build the FITConfiguration object from the answers gathered earlier.
 * Pure logic — no file IO — so it's easy to unit test (see
 * tests/build-fit-configuration.test.ts). Modelled on the example configs in
 * transactions-fit-performer/test-driver/.
 *
 * Run on its own:
 *   npx tsx src/workflows/fit-functional/steps/build-fit-configuration.ts
 *
 * Prints a sample generated config as JSON.
 */
import { isMain, runCli } from "../../../util/non-fit/cli.js";
import type { SelectedCluster } from "../../cluster/cluster-select/index.js";

/** Marks a config as generated by fit-cli. */
export const AUTO_GENERATED_MARKER = "Auto-generated by fit-cli";

/**
 * Produce a FITConfiguration object for a selected cluster. Capella clusters
 * (internal or production) use DNS SRV resolution, skip bucket creation and
 * don't expose the FIT proxy; self-managed clusters get the localhost-style
 * layout.
 */
export function buildFitConfiguration(cluster: SelectedCluster): Record<string, unknown> {
  const isCapella = cluster.flavour !== "self-managed";

  const clusterAccess: Record<string, unknown> = {
    defaultHostname: cluster.defaultHostname,
    connectionString: `${cluster.scheme}://\${defaultHostname}`,
    username: cluster.credentials.username,
    password: cluster.credentials.password,
    tls: cluster.tls,
    rest: {
      hostname: "${defaultHostname}",
      resolveDnsSrv: isCapella,
      ...(isCapella ? { port: 18091 } : {}),
    },
    ssh: null,
    proxy: isCapella ? null : { hostname: "localhost" },
  };

  // Capella clusters have no direct SSH access, so the ssh-tagged tests can't run;
  // realCapella tests need setup this generated config doesn't provide. Excluding
  // both mirrors the FITConfiguration.capella.example.json layout.
  const excludeTests = isCapella
    ? ["situational", "ssh", "realCapella"]
    : ["situational"];

  const config: Record<string, unknown> = {
    "//": AUTO_GENERATED_MARKER,
    clusterAccess,
    performerPorts: [8060],
    excludeTests,
  };

  if (isCapella) {
    config.skipBucketCreation = true;
  }

  return config;
}

if (isMain(import.meta.url)) {
  runCli(() => {
    const sample = buildFitConfiguration({
      scheme: "couchbase",
      defaultHostname: "localhost",
      flavour: "self-managed",
      credentials: { username: "Administrator", password: "password" },
      tls: null,
    });
    console.log(JSON.stringify(sample, null, 2));
    return Promise.resolve();
  });
}
