/**
 * Step: write the generated FITConfiguration.json into
 * transactions-fit-performer/test-driver/. If a config is already there and
 * wasn't generated by this tool, it's backed up (with a timestamp) first.
 *
 * Run on its own (dry run — reports the target path and whether a backup would
 * be made, without writing anything; add --root <dir> to point elsewhere):
 *   npx tsx src/workflows/fit-functional/steps/write-fit-configuration.ts
 */
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { isMain, runCli } from "../../../lib/cli.js";
import { FIT_PERFORMER, repoPath } from "../../../lib/repos.js";
import { rootDirFromArgv } from "../../../lib/root.js";
import { AUTO_GENERATED_MARKER } from "./build-fit-configuration.js";

/** Absolute path to the FITConfiguration.json this tool manages, under ROOT_DIR. */
export function fitConfigPath(rootDir: string): string {
  return join(repoPath(FIT_PERFORMER, rootDir), "test-driver", "FITConfiguration.json");
}

/** Absolute path to the FITConfiguration.md reference doc, under ROOT_DIR. */
export function fitConfigDocPath(rootDir: string): string {
  return join(repoPath(FIT_PERFORMER, rootDir), "test-driver", "FITConfiguration.md");
}

/** A filesystem-safe timestamp like 2026-06-03T12-34-56-789Z. */
function timestamp(): string {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

export interface WriteResult {
  /** Where the config was written. */
  path: string;
  /** Where the previous (non-generated) config was backed up, if it was. */
  backupPath?: string;
}

/**
 * Write `config` to {@link fitConfigPath}. If an existing file is present and
 * does not carry the auto-generated marker, it's copied to a timestamped backup
 * first so a hand-written config is never silently lost.
 */
export function writeFitConfiguration(
  config: Record<string, unknown>,
  rootDir: string,
): WriteResult {
  const path = fitConfigPath(rootDir);
  let backupPath: string | undefined;

  if (existsSync(path)) {
    const existing = readFileSync(path, "utf8");
    if (!existing.includes(AUTO_GENERATED_MARKER)) {
      backupPath = `${path}.backup-${timestamp()}`;
      copyFileSync(path, backupPath);
    }
  }

  writeFileSync(path, JSON.stringify(config, null, 2) + "\n");
  return { path, backupPath };
}

if (isMain(import.meta.url)) {
  runCli(() => {
    const { rootDir } = rootDirFromArgv(process.argv.slice(2));
    const path = fitConfigPath(rootDir);
    console.log(`Target: ${path}`);
    if (existsSync(path)) {
      const generated = readFileSync(path, "utf8").includes(AUTO_GENERATED_MARKER);
      console.log(
        generated
          ? "An auto-generated config already exists here — it would be overwritten without a backup."
          : "A non-generated config exists here — it would be backed up before being overwritten.",
      );
    } else {
      console.log("No config exists here yet — it would be created.");
    }
    return Promise.resolve();
  });
}
