/**
 * Step: build the FITConfiguration object from the answers gathered earlier.
 * Pure logic — no file IO — so it's easy to unit test (see
 * tests/build-fit-configuration.test.ts). Modelled on the example configs in
 * transactions-fit-performer/test-driver/.
 *
 * Run on its own:
 *   npx tsx src/workflows/fit-functional/util/build-fit-configuration.ts
 *
 * Prints a sample generated config as JSON.
 */
import { isMain, runCli } from "../../../util/non-fit/cli.js";
import { mergeConfigPieces, type ConfigPiece, type PieceData } from "../../../util/non-fit/config-pieces.js";
import type { SelectedCluster } from "../../cluster/cluster-select/cluster-select.js";
import { DEFAULT_PERFORMER_PORT } from "../../performers/util/performer-port.js";

/** Marks a config as generated by fit-cli. */
export const AUTO_GENERATED_MARKER = "Auto-generated by fit-cli";

/**
 * Produce a FITConfiguration object for a selected cluster. Capella clusters
 * (internal or production) use DNS SRV resolution, skip bucket creation and
 * don't expose the FIT proxy; self-managed clusters get the localhost-style
 * layout.
 *
 * `performerPort` is the host port the performer listens on (the `performerPorts`
 * entry test-driver connects to); it defaults to {@link DEFAULT_PERFORMER_PORT}.
 */
/**
 * The clusterAccess for a CNG / Protostellar cluster: the test-driver keeps a
 * classic couchbase:// `driver` connection for admin while the performer connects
 * to the gateway over couchbase2://. The FIT proxy doesn't support couchbase2 yet,
 * so it's null. Mirrors FITConfiguration.couchbase2.example.json.
 */
function cngClusterAccess(cluster: SelectedCluster & { cng: NonNullable<SelectedCluster["cng"]> }): PieceData {
  return {
    defaultHostname: cluster.defaultHostname,
    driver: {
      "//": "The driver connects with classic, which lets it create users, inspect cluster configs, etc.",
      connectionString: `${cluster.scheme}://\${defaultHostname}`,
      tls: cluster.tls,
    },
    performer: {
      connectionString: cluster.cng.performerConnectionString,
      tls: cluster.cng.tls,
    },
    username: cluster.credentials.username,
    password: cluster.credentials.password,
    rest: { hostname: "${defaultHostname}", resolveDnsSrv: false },
    ssh: null,
    "//": "The FIT proxy does not yet support couchbase2.",
    proxy: null,
  };
}

export function generatedFitConfigurationPiece(
  cluster: SelectedCluster,
  performerPort: number = DEFAULT_PERFORMER_PORT,
): ConfigPiece {
  if (cluster.cng) {
    return {
      label: "fit-cli generated CNG defaults",
      data: {
        "//": AUTO_GENERATED_MARKER,
        clusterAccess: cngClusterAccess({ ...cluster, cng: cluster.cng }),
        performerPorts: [performerPort],
        excludeTests: ["situational"],
      },
    };
  }

  const isCapella = cluster.flavour !== "self-managed";

  const clusterAccess: PieceData = {
    defaultHostname: cluster.defaultHostname,
    connectionString: `${cluster.scheme}://\${defaultHostname}`,
    username: cluster.credentials.username,
    password: cluster.credentials.password,
    tls: cluster.tls,
    rest: {
      hostname: "${defaultHostname}",
      resolveDnsSrv: isCapella,
      ...(isCapella ? { port: 18091 } : {}),
    },
    ssh: null,
    proxy: isCapella
      ? null
      : {
          "//":
            "The performer is running in Docker and needs to be able to connect to the FIT proxy (the test-driver) running on the host machine",
          hostname: "host.docker.internal",
        },
  };

  // Capella clusters have no direct SSH access, so the ssh-tagged tests can't run;
  // realCapella tests need setup this generated config doesn't provide. Excluding
  // both mirrors the FITConfiguration.capella.example.json layout.
  const excludeTests = isCapella
    ? ["situational", "ssh", "realCapella"]
    : ["situational"];

  const data: PieceData = {
    "//": AUTO_GENERATED_MARKER,
    clusterAccess,
    performerPorts: [performerPort],
    excludeTests,
  };

  if (isCapella) {
    data.skipBucketCreation = true;
  }

  return { label: "fit-cli generated defaults", data };
}

export function runtimeFitConfigurationPiece(cluster: SelectedCluster): ConfigPiece {
  return {
    label: "fit-cli runtime cluster fields",
    data: {
      clusterAccess: {
        defaultHostname: cluster.defaultHostname,
      },
    },
  };
}

export function buildFitConfiguration(
  cluster: SelectedCluster,
  performerPort: number = DEFAULT_PERFORMER_PORT,
  fitConfigPiece?: PieceData,
): Record<string, unknown> {
  return mergeConfigPieces([
    generatedFitConfigurationPiece(cluster, performerPort),
    ...(fitConfigPiece ? [{ label: "definition fitConfig piece", data: fitConfigPiece }] : []),
    ...(fitConfigPiece ? [runtimeFitConfigurationPiece(cluster)] : []),
  ]);
}

if (isMain(import.meta.url)) {
  runCli(() => {
    const sample = buildFitConfiguration({
      scheme: "couchbase",
      defaultHostname: "localhost",
      flavour: "self-managed",
      credentials: { username: "Administrator", password: "password" },
      tls: null,
    });
    console.log(JSON.stringify(sample, null, 2));
    return Promise.resolve();
  });
}
