/**
 * Step: build the FITConfiguration object from the answers gathered earlier.
 * Pure logic — no file IO — so it's easy to unit test (see
 * tests/build-fit-configuration.test.ts). Modelled on the example configs in
 * transactions-fit-performer/test-driver/.
 *
 * Run on its own:
 *   npx tsx src/fit/functional/util/build-fit-configuration.ts
 *
 * Prints a sample generated config as JSON.
 */
import { isMain, runCli } from "../../../util/non-fit/cli.js";
import { mergeConfigPieces, type ConfigPiece, type PieceData } from "../../../util/non-fit/config-pieces.js";
import type { SelectedCluster } from "../../../cluster/cluster-select/cluster-select.js";
import { DEFAULT_PERFORMER_PORT } from "../../performers/util/performer-port.js";

/** Marks a config as generated by fit-cli. */
export const AUTO_GENERATED_MARKER = "Auto-generated by fit-cli";

/**
 * Return the first hostname from a (potentially comma-separated) hostname list.
 * The connection string can carry multiple bootstrap nodes, but REST and similar
 * single-host fields must be given just one address.
 */
export function firstHostname(defaultHostname: string): string {
  return defaultHostname.split(",")[0]?.trim() ?? defaultHostname.trim();
}

/**
 * Produce a FITConfiguration object for a selected cluster. Capella clusters
 * (internal or production) use DNS SRV resolution, skip bucket creation and
 * don't expose the FIT proxy; self-managed clusters get the localhost-style
 * layout.
 *
 * `performerPort` is the host port the performer listens on (the `performerPorts`
 * entry test-driver connects to); it defaults to {@link DEFAULT_PERFORMER_PORT}.
 */
/**
 * The clusterAccess for a CNG / OpenShift cluster.
 *
 * On OpenShift (ROSA), Couchbase is exposed via TLS-passthrough routes on port 443 only.
 * There is no external KV (memcached) port — only HTTPS management and the couchbase2
 * gateway.  The driver therefore cannot use a classic couchbase:// connection (KV bootstrap
 * would stall), so we use the flat `connectionString: couchbase2://…` structure matching
 * the GHA workflow (fit-app-deployment PR #123).  The test-driver uses couchbase2 directly
 * and skips bucket creation (the bucket is pre-created by cbdinocluster / the cluster spec).
 *
 * The REST field uses the management UI hostname (bare, no port) + explicit port 443 so the
 * test-driver's HTTP client reaches the management API on the correct port.
 */
function cngClusterAccess(cluster: SelectedCluster & { cng: NonNullable<SelectedCluster["cng"]> }): PieceData {
  const firstHost = firstHostname(cluster.defaultHostname);
  // Strip any :port suffix — rest.hostname must be a bare hostname; the port goes in rest.port.
  const restHostname = firstHost.replace(/:\d+$/, "");
  // Extract the explicit port from defaultHostname to use as rest.port (defaults to 18091 for
  // couchbases:// but OpenShift routes expose on 443).
  const portMatch = /:\d+$/.exec(firstHost);
  const restPort = portMatch ? parseInt(portMatch[0].slice(1), 10) : undefined;
  return {
    defaultHostname: cluster.defaultHostname,
    connectionString: cluster.cng.performerConnectionString,
    tls: cluster.cng.tls,
    username: cluster.credentials.username,
    password: cluster.credentials.password,
    rest: { hostname: restHostname, resolveDnsSrv: false, ...(restPort !== undefined ? { port: restPort } : {}) },
    ssh: null,
    "//": "The FIT proxy does not yet support couchbase2.",
    proxy: null,
  };
}

export function generatedFitConfigurationPiece(
  cluster: SelectedCluster,
  performerPort: number = DEFAULT_PERFORMER_PORT,
): ConfigPiece {
  if (cluster.cng) {
    return {
      label: "fit-cli generated CNG defaults",
      data: {
        "//": AUTO_GENERATED_MARKER,
        clusterAccess: cngClusterAccess({ ...cluster, cng: cluster.cng }),
        performerPorts: [performerPort],
        excludeTests: ["situational"],
        // The bucket is pre-created in the CouchbaseCluster spec; the driver must not try to
        // create it via classic management (there is no external KV or mgmt port on OpenShift).
        skipBucketCreation: true,
      },
    };
  }

  const isCapella = cluster.flavour !== "self-managed";

  const clusterAccess: PieceData = {
    defaultHostname: cluster.defaultHostname,
    connectionString: `${cluster.scheme}://\${defaultHostname}`,
    username: cluster.credentials.username,
    password: cluster.credentials.password,
    tls: cluster.tls,
    rest: {
      hostname: isCapella ? "${defaultHostname}" : firstHostname(cluster.defaultHostname),
      resolveDnsSrv: isCapella,
      ...(isCapella ? { port: 18091 } : {}),
    },
    ssh: null,
    proxy: isCapella
      ? null
      : {
          "//":
            "The performer is running in Docker and needs to be able to connect to the FIT proxy (the test-driver) running on the host machine",
          hostname: "host.docker.internal",
        },
  };

  // Capella clusters have no direct SSH access, so the ssh-tagged tests can't run;
  // realCapella tests need setup this generated config doesn't provide. Excluding
  // both mirrors the FITConfiguration.capella.example.json layout.
  const excludeTests = isCapella
    ? ["situational", "ssh", "realCapella"]
    : ["situational"];

  const data: PieceData = {
    "//": AUTO_GENERATED_MARKER,
    clusterAccess,
    performerPorts: [performerPort],
    excludeTests,
  };

  if (isCapella) {
    data.skipBucketCreation = true;
  } else {
    // numReplicas >= 1 is required for FTS tests to pass.
    data.bucketConfig = { numReplicas: 1, bucketType: "couchbase", storage: "couchstore" };
  }

  return { label: "fit-cli generated defaults", data };
}

export function runtimeFitConfigurationPiece(cluster: SelectedCluster): ConfigPiece {
  const firstHost = firstHostname(cluster.defaultHostname);
  const restHostname = firstHost.replace(/:\d+$/, "");
  const portMatch = /:\d+$/.exec(firstHost);
  const restPort = portMatch ? parseInt(portMatch[0].slice(1), 10) : undefined;
  return {
    label: "fit-cli runtime cluster fields",
    data: {
      clusterAccess: {
        defaultHostname: cluster.defaultHostname,
        rest: {
          hostname: restHostname,
          ...(restPort !== undefined ? { port: restPort } : {}),
        },
      },
    },
  };
}

export function buildFitConfiguration(
  cluster: SelectedCluster,
  performerPort: number = DEFAULT_PERFORMER_PORT,
  fitConfigPiece?: PieceData,
): Record<string, unknown> {
  return mergeConfigPieces([
    generatedFitConfigurationPiece(cluster, performerPort),
    ...(fitConfigPiece ? [{ label: "definition fitConfig piece", data: fitConfigPiece }] : []),
    ...(fitConfigPiece ? [runtimeFitConfigurationPiece(cluster)] : []),
  ]);
}

if (isMain(import.meta.url)) {
  runCli(() => {
    const sample = buildFitConfiguration({
      scheme: "couchbase",
      defaultHostname: "localhost",
      flavour: "self-managed",
      credentials: { username: "Administrator", password: "password" },
      tls: null,
    });
    console.log(JSON.stringify(sample, null, 2));
    return Promise.resolve();
  });
}
