/**
 * The shape of a `fit` YAML definition file.
 */
import type { PortInUsePolicy } from "../../performers/util/performer-port.js";
import type { CapellaCloudProvider, CbdinoclusterDef } from "../../../cluster/cluster-create/build-cluster-def.js";
import type { ClusterExistsPolicy } from "../../../cluster/cluster-create/cluster-exists-policy.js";
import type { PieceData } from "../../../util/non-fit/config-pieces.js";

export const FIT_DEFINITION_TYPE = "fit";
export const CURRENT_FIT_DEFINITION_VERSION = 1;
export const FIT_RUN_TYPES = ["functional", "situational", "analytics-functional"] as const;

export type FitRunType = (typeof FIT_RUN_TYPES)[number];
export type FitConfigPiece = PieceData;
export type ClusterTls = null | { insecure: true } | { certPath: string };

export interface ConnectionClusterSetup {
  connectionString: string;
  username: string;
  password: string;
  tls?: ClusterTls;
}

export type UseExistingClusterSetup = Record<string, never>;

/**
 * How to prepare `~/.cbdinocluster` on the box before allocating.
 *
 * Carries an editable `args` string — the arguments passed to `cbdinocluster init`
 * (e.g. `--auto --disable-k8s --docker-network fit`) so the box self-installs its
 * config. fit-cli appends the GitHub credentials at runtime (kept out of the
 * definition file). `configPatch` is merged onto `~/.cbdinocluster` after init
 * runs, for config `cbdinocluster init` can't express via flags — e.g.
 * situational's `capella`/`aws` blocks, or CNG's `k8s` block (injected at runtime
 * from the logged-in OpenShift context). `config` uploads a verbatim object as
 * `~/.cbdinocluster` (legacy back-compat; not generated by fit-cli). At most one of
 * `args`/`config` is present; `configPatch` requires `args`.
 */
export interface CbdinoclusterInitSetup {
  args?: string;
  config?: PieceData;
  configPatch?: PieceData;
}

/**
 * Build cbdinocluster from a pull request instead of downloading the latest
 * release. `pr` is the PR number against the canonical `couchbaselabs/cbdinocluster`
 * repo; `repo` overrides to a fork (`owner/repo`).
 */
export interface CbdinoclusterSourceGit {
  pr: number;
  repo?: string;
}

/**
 * Where to get the cbdinocluster binary. When absent the latest published GitHub
 * release is used (default behaviour). When present, the binary is built from the
 * PR's HEAD on the remote box itself — always the right OS/arch, no local binary needed.
 */
export interface CbdinoclusterSource {
  git: CbdinoclusterSourceGit;
}

/**
 * Declares that this cluster should be created as a Capella cloud cluster via
 * cbdinocluster's `cloud` deployer. `cloudProvider` specifies where Capella
 * should deploy the underlying infrastructure; `environment` selects the
 * Capella control-plane (a key under `capella` in environments.json5 — e.g.
 * "dev", "stage"). fit-cli derives the cbdinocluster init args and deployer
 * from this block at runtime; neither needs to appear in the definition file.
 */
export interface CapellaClusterSetup {
  cloudProvider: CapellaCloudProvider;
  /** Capella environment to create this cluster in. Defaults to "dev". */
  environment?: string;
}

export interface CbdinoclusterSetup {
  config: CbdinoclusterDef;
  onClusterExists?: ClusterExistsPolicy;
  deployer?: string;
  /** When present, this cluster is a Capella cloud cluster. */
  capella?: CapellaClusterSetup;
}

/**
 * Per-instance setup applied once to the box before any cluster or run. The
 * cbdinocluster `init` lives here (not under each cluster) because `cbdinocluster
 * init` configures `~/.cbdinocluster` once per instance — every cluster on the
 * instance then allocates against that same config.
 */
export interface InstanceSetup {
  cbdinocluster?: {
    /** Where to get the binary. Omit to use the latest published release. */
    source?: CbdinoclusterSource;
    /** How to init ~/.cbdinocluster. Omit to run the standard docker-only init. */
    init?: CbdinoclusterInitSetup;
  };
  /**
   * Capella environment this instance's clusters are created in (a key under
   * `capella` in environments.json5 — e.g. "dev", "stage"). Lives here because
   * `cbdinocluster init` configures one `~/.cbdinocluster` (and so one Capella
   * identity) per instance/box. Defaults to "dev".
   */
  capellaEnvironment?: string;
}

/**
 * Private endpoint (PrivateLink) mode for an AWS instance. When present, the
 * instance is launched into the cbqerunners VPC default SG (opened intra-VPC) so
 * the box and the Capella private endpoint can reach each other.
 *
 * `instanceProfile` names the IAM instance profile that grants the box
 * CreateVpcEndpoint + Route53 permissions at runtime (provisioned by
 * sdkqe-github-runners-tf). Omit to skip profile attachment (networking only —
 * the VPC endpoint creation by the FIT test will fail without a profile).
 */
export interface PrivateEndpointSetup {
  instanceProfile?: string;
}

export interface AwsInstanceSetup {
  instanceType?: string;
  /** Present when this instance should support private endpoint (PrivateLink) testing. */
  privateEndpoint?: PrivateEndpointSetup;
}

export type InstanceMode =
  | { aws: AwsInstanceSetup }
  | { localhost: Record<string, never> };

export interface RepoSetup {
  gerritRef?: string;
}

export interface ReposSetup {
  "transactions-fit-performer"?: RepoSetup;
}

export interface SharedSetup {
  repos?: ReposSetup;
}

export interface PerformerSetup {
  /**
   * Full prebuilt performer image, `<sdk>-fit-performer:<tag>` (e.g.
   * `java-fit-performer:main` or `java-fit-performer:refs-changes-18-195818-7`).
   * The SDK is derived from the image prefix; only JVM and C++ SDKs publish
   * these images. fit-cli prepends the GHCR registry/owner at run time.
   */
  image: string;
  port?: number;
  onPortInUse?: PortInUsePolicy;
}

/** Named test presets that expand to a set of test classes. */
export const TEST_PRESETS = ["all", "all-transactions", "all-non-transactions", "standard-qe"] as const;
export type TestPreset = (typeof TEST_PRESETS)[number];

export interface MavenOptions {
  args?: string[];
  runDisabledTests?: boolean;
}

/**
 * Which test-driver tests a run executes. The final set is the union of every
 * preset's expansion with the explicit `classes`. Presets like
 * `all-transactions` are expanded against the listed tests at run time; an
 * `all` preset (or omitting both keys) means "run everything". `classes` lists
 * fully-qualified test class names (or `Class#method` selectors) to add on top.
 * `packages` lists Java package prefixes; each is expanded to a `pkg.*` Maven
 * wildcard selector and unioned with `classes`.
 */
export interface TestsSection {
  presets?: TestPreset[];
  packages?: string[];
  classes?: string[];
  /**
   * Replaces the built-in default excluded Maven groups outright. Mutually
   * exclusive with `addToDefaultExcludedGroups`.
   */
  excludedGroups?: string[];
  /**
   * Adds these groups on top of the built-in defaults (the common case when a
   * preset just needs one extra exclusion). Mutually exclusive with
   * `excludedGroups`.
   */
  addToDefaultExcludedGroups?: string[];
  maven?: MavenOptions;
}

export const SITUATIONAL_DATABASE_MODES = ["hosted", "local"] as const;
export type SituationalDatabaseMode = (typeof SITUATIONAL_DATABASE_MODES)[number];

export interface SituationalDatabaseSetup {
  mode: SituationalDatabaseMode;
  /**
   * Which results environment to store/view results in (a key under `results` in
   * environments.json5 — e.g. "dev"=faas, "prod"=performance-sdk). Only meaningful
   * when mode is "hosted". Defaults to "dev".
   */
  resultsEnvironment?: string;
}

export interface SituationalSection {
  database: SituationalDatabaseSetup;
}

export interface FunctionalRun {
  type: "functional";
  fitConfig?: ResolvedFitConfig | string;
  tests: TestsSection;
  /** Run this entry N times in sequence against the same cluster. */
  repeat?: number;
}

export interface SituationalRun {
  type: "situational";
  fitConfig?: ResolvedFitConfig | string;
  situational: SituationalSection;
  tests: TestsSection;
  /** Run this entry N times in sequence. */
  repeat?: number;
}

/**
 * A functional run that tests an Analytics product — Enterprise Analytics or
 * Capella Analytics — via the `columnar-test-driver` Maven module (query,
 * connection and auth tests) rather than the operational `test-driver`. Like
 * {@link FunctionalRun} it is cluster-bound; what is being tested is expressed by:
 *   - the cluster: a cbdinocluster `columnar: true` block (a self-managed
 *     Enterprise Analytics cluster), or a connection to a Capella Analytics cluster;
 *   - the performer image: a Columnar SDK or an Enterprise Analytics SDK;
 *   - the connection details on the fitConfig (driver vs performer), as for CNG.
 */
export interface AnalyticsFunctionalRun {
  type: "analytics-functional";
  fitConfig?: ResolvedFitConfig | string;
  tests: TestsSection;
  /** Run this entry N times in sequence against the same cluster. */
  repeat?: number;
}

export type FitRun = FunctionalRun | SituationalRun | AnalyticsFunctionalRun;

export interface SessionLifetime {
  performer: PerformerSetup;
  runs: FitRun[];
}

export interface ClusterLifetime {
  connection?: ConnectionClusterSetup;
  useExisting?: UseExistingClusterSetup;
  cbdinocluster?: CbdinoclusterSetup;
  clusterConfig?: string;
  sessions: SessionLifetime[];
}

export interface ClusterConfigRef {
  id: string;
  cbdinocluster?: CbdinoclusterSetup;
  connection?: ConnectionClusterSetup;
  useExisting?: UseExistingClusterSetup;
}

/** Connection scheme for a FIT driver or performer. */
export type ConnectionScheme = "couchbase" | "couchbases" | "couchbase2";

/** Per-component (driver or performer) scheme and TLS overrides. */
export interface SchemeAndTls {
  /** Protocol scheme for the SDK connection string. */
  scheme?: ConnectionScheme;
  /**
   * TLS config for this component.  `null` disables TLS; omit to inherit the
   * top-level tls setting.
   */
  tls?: { insecure?: boolean; cert?: string } | null;
}

/**
 * Declares the SDK connection scheme(s) fit-cli should write into
 * `clusterAccess` in FITConfiguration.json.  When absent, fit-cli infers the
 * scheme from the cluster type (`cao` → couchbase2, else classic).
 *
 * `scheme` / `tls` at the top level apply to both driver and performer unless
 * overridden by the `driver` / `performer` sub-objects — matching the
 * FITConfiguration `driver` / `performer` override structure described in
 * FITConfiguration.md.
 */
export interface FitConnectionSpec {
  scheme?: ConnectionScheme;
  tls?: { insecure?: boolean; cert?: string } | null;
  /** Override the scheme/TLS for only the test-driver side. */
  driver?: SchemeAndTls;
  /** Override the scheme/TLS for only the performer side. */
  performer?: SchemeAndTls;
}

export interface FitConfigRef {
  id: string;
  /** Fields merged into FITConfiguration.json and printed to the console. */
  config?: FitConfigPiece;
  /**
   * Declares the connection scheme(s) fit-cli should use when generating
   * `clusterAccess` in FITConfiguration.json.  When absent, fit-cli infers
   * from the cluster type.
   */
  connection?: FitConnectionSpec;
  /**
   * Raw FITConfiguration.json partial merged in last (highest priority).
   * Unlike `config`, this is NOT printed to the console — use it for values
   * that are verbose or sensitive (certificates, tokens).
   */
  patch?: FitConfigPiece;
}

/**
 * The resolved form of a fitConfig entry — carries `config`, `connection`, and
 * `patch` together.  In a parsed `FitRun`, `fitConfig` starts as
 * `ResolvedFitConfig | string`; `resolveDefinitionRefs` replaces the string
 * (ref id) with the full resolved object.
 */
export interface ResolvedFitConfig {
  /** Merged into FITConfiguration.json and printed to the console. */
  config?: PieceData;
  /** Declares the connection scheme(s); overrides fit-cli's auto-detection. */
  connection?: FitConnectionSpec;
  /** Merged into FITConfiguration.json last (highest priority); NOT printed to the console. */
  patch?: PieceData;
}

export type InstanceLifetime =
  & InstanceMode
  & {
    setup?: InstanceSetup;
    clusters: ClusterLifetime[];
    clusterlessSessions?: SessionLifetime[];
  };

export interface FitDefinition {
  version: number;
  type: typeof FIT_DEFINITION_TYPE;
  description?: string;
  instances: InstanceLifetime[];
  setup?: SharedSetup;
  clusterConfigs?: ClusterConfigRef[];
  fitConfigs?: FitConfigRef[];
}
