/**
 * Step: write the generated FITConfiguration.json to a fresh file in the
 * current run directory under /tmp/fit-cli so test-driver can consume it via
 * `-Dfit.config=<path>`.
 *
 * Run on its own (dry run — reports where a fresh file would be written):
 *   npx tsx src/workflows/fit-shared/fit-configuration/write-fit-configuration.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { artifactFromPath, type Artifact } from "../../../util/non-fit/artifacts.js";
import { isMain, runCli } from "../../../util/non-fit/cli.js";
import { ensureRunDir, iterationRunDir } from "../../../util/non-fit/replay.js";
import { FIT_PERFORMER, repoPath } from "../../../util/fit/repos.js";
import { rootDirFromArgv } from "../../../util/fit/root.js";

/** Marks a FITConfiguration as generated by fit-cli (shared across FIT flavours). */
export const AUTO_GENERATED_MARKER = "Auto-generated by fit-cli";

/**
 * Absolute path to the FITConfiguration.json for a specific cycle and iteration
 * in the current run directory.
 */
export function fitConfigPath(cycleIndex: number = 0, iteration: number = 0, runDir: string = ensureRunDir()): string {
  return join(iterationRunDir(cycleIndex, iteration, runDir), "FITConfiguration.json");
}

/** Absolute path to the FITConfiguration.md reference doc, under ROOT_DIR. */
export function fitConfigDocPath(rootDir: string): string {
  return join(repoPath(FIT_PERFORMER, rootDir), "test-driver", "FITConfiguration.md");
}

export interface WriteResult {
  /** Where the config was written. */
  path: string;
  /** Artifact metadata for the written config file. */
  artifact: Artifact;
}

/** Write `config` to a fresh file in the current run directory and return its path. */
export function writeFitConfiguration(
  config: Record<string, unknown>,
  runDir: string = ensureRunDir(),
  cycleIndex: number = 0,
  iteration: number = 0,
): WriteResult {
  const itDir = iterationRunDir(cycleIndex, iteration, runDir);
  mkdirSync(itDir, { recursive: true, mode: 0o700 });
  const path = join(itDir, "FITConfiguration.json");
  writeFileSync(path, JSON.stringify(config, null, 2) + "\n");
  return {
    path,
    artifact: artifactFromPath(path, "Generated FITConfiguration.json for the FIT test-driver", runDir),
  };
}

if (isMain(import.meta.url)) {
  runCli(() => {
    rootDirFromArgv(process.argv.slice(2));
    console.log(`A generated config would be written to a fresh file like:\n${fitConfigPath(0, 0)}`);
    return Promise.resolve();
  });
}
